spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionale
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: postgres
      password: admin
      roles: USER, ADMIN
  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.gestionale: DEBUG

jwt:
  secret: your_jwt_secret
  expiration: 3600